language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    
install:
  - mvn clean compile -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true

script:
  - mvn package -DskipTests

branch:
  only:
    - master
    
