language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    
install:
  - mvn clean compile -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.failOnViolation=false -Denforcer.fail=false

script:
  - mvn package -DskipTests

before_deploy:
  - export RELEASE_FILE=$(ls target/*.hpi)
  - echo "Deploying $RELEASE_FILE to GitHub"

deploy:
  provider: releases
  api_key:
    secure: dfsh7jMdMLHxz/OS6yr3poRF/uC43nuTw2cx44+gCoasXGwEPOsH9x61/qQdiSag1DIDVga7RKRAnkIJoqafwdgR41VIo6ot7w0Co3LGu1q/yVhWO8t1ou29Dn5lVAz9Wt41EBF492zHjxW0+TVEGAn2a+x5CJKZP2R9/TOvJjbq09bwuNBEzgDglU9erNeNLvKHZd2+jC2Obe/HSP6W5Eho6iUFpc1rsHr8bdVoYtCeVHxenOK19/3tUAzlpUOOWLSljp1XUNpt0ATx/Vn0AR+L3VsJVLd/nH7o4NVQk8vfn7ExLm8InLcMd+sCaav54CamVSZuGNR2Y5CcwD/rnBIiO1V+NW/2nRYveGn2N6SWGJd++tGDFIZCVRkQn+7TXQj31ohLpHJ4gGO3/OfLTPST75be18q52AK/uw/0nPA/V1vMDUJsZPZe18XZU0WoQpHU2OD843Zk5lFRufSqSinYjmf2ukTq+gyrCuh1D3ivzOxMO5B4QM9YpdpfmIBtvmMgNE+dE3f6gcyYpahQ289nsbhWl+o3XZHXDnLR8WDXv89kjFLraAUXj4JAwUygww4TwX0VOrYSf1rpyjUwdulvzX00cEsrOEBwdgL7OT1dfchAHGIKWJ+gfe73HgYCIw4owiU+rdQMAzMZ/TO31PypmYTvtPS5y3fLaaWIydQ=
  file:
    - "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    repo: STAMP-project/dspot-jenkins-plugin
    tags: true

branch:
  only:
    - master
    
