language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    
install:
  - mvn clean compile -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true

script:
  - mvn package -DskipTests
 
before_deploy:
  - export RELEASE_FILE=$(ls target/*.hpi)
  - echo "Deploying $RELEASE_FILE to GitHub"
  
deploy:
  provider: releases
  api_key: "${env.GITHUB_TOKEN}" 
  file:
    - "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true

branch:
  only:
    - master
    
